version: '2.7'

rpc:
    listen: tcp://127.0.0.1:6001

server:
    command: "php app.php"
    relay: pipes
    on_init:
        command: "php app.php configure"

jobs:
    consume: [ default ]
    pipelines:
        default:
            driver: memory
            config: { }
    pool:
        num_workers: 16

temporal:
    address: temporal:7233
    namespace: default
    activities:
        num_workers: 4

logs:
    level: info
    channels:
        server:
            level: info
